version: '3'

services:
  app:
    image: nextcloud
    ports:
      - 80:80
    volumes:
      - ./nextcloud:/var/www/html
      - ./nextcloud-data:/var/www/html/data
    restart: always

volumes:
  nextcloud:
  nextcloud-data:
